apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: gustavokubiack/hello-fastapi-k8s
  newName: gustavokubiack/hello-fastapi-k8s
  newTag: 176d2de4bbffc2a94cf01ee4a0a38ceb6992a167
- name: hello-fastapi
  newName: gustavokubiack/hello-fastapi-k8s
  newTag: 62ca3a177535d87d1913aadb9c95725c9c3b7573
